export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ACCOUNTING_TEST = 'ACCOUTING_TEST';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_ERROR = 'FETCH_DATA_ERROR';
export const SUBMIT_INPUT_SET_DATA = 'SUBMIT_INPUT_SET_DATA';
export const ADD_INPUT_SET_STATE = 'ADD_INPUT_SET_STATE';
export const DELETE_CATEGORY_SET_STATE = 'DELETE_CATEGORY_SET_STATE';
export const DELETE_ITEM_SET_STATE = 'DELETE_ITEM_SET_STATE';
export const SET_MONTH_ID = 'SET_MONTH_ID';
export const ON_MODAL_INPUT = 'ON_MODAL_INPUT';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_DATA = 'SET_DATA';
export const SET_SECTION = 'SET_SECTION';
export const DISABLE_BUTTON = 'DISABLE_BUTTON';
export const ENABLE_BUTTON = 'ENABLE_BUTTON';
export const SET_BALANCE = 'SET_BALANCE';

